default:
  image: python:3.12

stages:
  - lint
  - test
  - publish

flake8:
  stage: lint
  script:
    - pip install poetry
    - poetry install --no-root
    - poetry run flake8 .
  only:
    - merge_requests
    - main

black:
  stage: lint
  script:
    - pip install poetry
    - poetry install --no-root 
    - poetry run black --check .
  only:
    - merge_requests
    - main

# pylint:
#   stage: lint
#   script:
#     - pip install poetry
#     - poetry install --no-root 
#     - poetry run pylint src tests
#   only:
#     - merge_requests
#     - main

isort:
  stage: lint
  script:
    - pip install poetry
    - poetry install --no-root 
    - poetry run isort src tests --check-only
  only:
    - merge_requests
    - main

unit-tests:
  stage: test
  script:
    - pip install poetry
    - poetry install
    - poetry run pytest
  only:
    - merge_requests
    - main

coverage:
  stage: test
  dependencies:
    - unit-tests
  script:
    - pip install poetry
    - poetry install
    - >
      poetry run pytest
      --cov=src
      --cov-report=term
      --cov-report=html:coverage
      --cov-report=xml:coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - 'coverage/*'
  only:
    - merge_requests
    - main

pages:
  stage: publish
  dependencies:
    - coverage
  script:
    - ls coverage/
    - mv coverage/ public/
  artifacts:
    name: public
    paths:
      - public
  only:
    - main
