# If this section is omitted,
# logging capabilities would be disabled.
logs:
  level: WARNING # DEBUG | INFO | WARNING | ERROR | CRITICAL
  stdout: true
  location: ~/.nimbus/logs

reports:
  format: txt
  location: ~/.nimbus/reports

# Collections of individual profiles, 
# each tailored to configure a specific archiver.
archivers:
  rar-protected:
    provider: rar
    password: SecretPwd # Password, to protect the archive with
    recovery: 3         # Add 3% recovery data
    compression: 0      # Compression level [0-5]

# Collections of individual profiles, 
# each tailored to configure a specific uploader.
uploaders:
  aws-archive:
    provider: aws
    access_key: XXXXXXXXXXXXXXXXXXXX
    secret_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    bucket: my.domain.archive
    storage_class: DEEP_ARCHIVE # STANDARD | INTELLIGENT_TIERING | DEEP_ARCHIVE

# Service configuration with emphasis on 
# service discovery and environment setup.
services:
  # Each directory is recursively traversed 
  # in search of a supported services.
  directories:
    - ~/services
    - /mnt/ssd/services

# Secrets Configuration Mapping for Services
# In this section, we define how secrets are mapped to services. 
# Each service is evaluated against a sequence of glob patterns. 
# When multiple patterns match, the values are combined into a single set. 
# The approach used is “last-match-overwrites” 
# meaning that the last matching value takes precedence.
secrets:
  # Match any service
  - service: "*"
    environment:
      UID: 1001
      GID: 1001
      TZ: "America/New_York"
      SMTP_SERVER: "smtp.server.com"
      SMTP_PORT: "587"
      SMTP_USERNAME: "username"
      SMTP_PASSWORD: "password"
      SMTP_DOMAIN: "domain.com"

  # Match a service that starts with 'git'
  - service: "git*"
    environment:
      UID: 1002 # Overwrite the value
      GID: 1002

  # Match exact 'gitlab' service name
  - service: "gitlab"
    environment:
      GITLAB_HTTP_PORT: 8080
      GITLAB_SSH_PORT: 8022

# Serves as a structured framework for managing 
# and standardizing backup processes, 
# enhancing data preservation and retrieval.
backup:
  destination: /mnt/backups
  archiver: rar-protected
  uploader: aws-archive
  directories: 
    apps:
      - /mnt/ssd/apps/gitlab
      - /mnt/ssd/apps/nextcloud
      - /mnt/ssd/apps/plex
    media:
      - ~/Music
      - ~/Videos
      - /mnt/hdd/music
      - /mnt/hdd/books
    photos:
      - ~/Photos
      - /mnt/hdd/photos
    docs:
      - ~/Documents
   