
# Archiver profiles
archivers:
  rar-protected: # archiver profile
    provider: rar
    password: SuperSecretPassword

# Uploader profiles
uploaders:
  aws-archive: # uploader profile
    provider: aws
    access_key: XXXXXXXXXXXXXXXXXXXX
    secret_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    bucket: my.domain.archive
    storage_class: DEEP_ARCHIVE # STANDARD | INTELLIGENT_TIERING | DEEP_ARCHIVE

services:
  # This could be either a parent directory with a nested services, 
  # or a full path to a directory with a single service.
  docker-compose: 
    - ~/services
    - /path/to/directory

backups:
  destination: /mnt/backups
  archiver: rar-protected # profile
  uploader: aws-archive # profile
  directories: 
    config: # group
      - ~/.ssh
      - /path/to/some/config/folder
    docs:
      - ~/Documents
    apps:
      - /mnt/ssd/nextcloud/
      - /mnt/ssd/gitlab
      - /mnt/ssd/syncthing
    media:
      - ~/Pictures
      - ~/Music
      - ~/Videos
