report:
  location: ~/reports
  format: txt


# Collections of individual profiles, 
# each tailored to configure a specific archiver.
archivers:
  rar-protected:
    provider: rar
    password: SuperSecretPassword

# Collections of individual profiles, 
# each tailored to configure a specific uploader.
uploaders:
  aws-archive:
    provider: aws
    access_key: XXXXXXXXXXXXXXXXXXXX
    secret_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    bucket: my.domain.archive
    storage_class: DEEP_ARCHIVE # STANDARD | INTELLIGENT_TIERING | DEEP_ARCHIVE

# Service configuration with emphasis on 
# service discovery and environment setup.
services:
  discovery:
    # Each directory is recursively traversed 
    # in search of a supported services.
    directories:
      - ~/services
      - /mnt/ssd/services

  # Overwrite and customize environment configuration
  # on a per-service basis.
  environment:
    gitlab:
      GITLAB_HTTP_PORT: 8080
      GITLAB_SSH_PORT: 8022

# Serves as a structured framework for managing 
# and standardizing backup processes, 
# enhancing data preservation and retrieval.
backups:
  destination: /mnt/backups
  archiver: rar-protected
  uploader: aws-archive
  directories: 
    apps:
      - /mnt/ssd/apps/gitlab
      - /mnt/ssd/apps/nextcloud
      - /mnt/ssd/apps/plex
    media:
      - ~/Music
      - ~/Videos
      - /mnt/hdd/music
      - /mnt/hdd/books
    photos:
      - ~/Photos
      - /mnt/hdd/photos
    docs:
      - ~/Documents
   